trigger:
 - none
stages:
- stage: Build
  jobs:
   - job: Build
     pool: 
      name: "Azure Pipelines"
     steps:
     - task: Npm@1
       displayName: "npm install"
       inputs:
         command: install
     - task: ArchiveFiles@2
       inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
     - task: PublishBuildArtifacts@1
       displayName: "Publish artifact"
       inputs:
         PathtoPublish: "$(Build.ArtifactStagingDirectory)"
         publishLocation: "container"
         ArtifactName: nodejs
- stage: Deploy
  jobs:
  - job: Deploy
    pool: 
     name: "Azure Pipelines"
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: "download artifacts"
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        itemPattern: '**/*.zip'
        downloadPath: '$(System.ArtifactsDirectory)'   
    - task: AzureRMWebAppDeployment@4
      inputs:
       ConnectionType: AzureRM
       azureSubscription: "Free Trial (0842a7ee-3fe3-4df8-a868-313b0d4adf3a)"
       packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
       appType: webAppLinux
       WebAppName: 'nodejs-final'
    
        
        

